### ISSUE TITLE
wrong pool state

### ISSUE THREAD

**Issue by smash-necros** [Charlie85270/conflux-pos-pools#12]
Hi
Cozak pos pool showing offline on a site, but it's not.
https://cozak.space

**Comment by Charlie85270** [comment]
Hey, the address of your pool wasn't good (`accfmrzvjgn6hzutp1m5kp4tcbuhhwyggy4x0j99v1` instead of `cfx:acfmcjhvgwm3rp1h3d10kuj700ayv9szmjjskkep1s`). 
I updated the pools.json file, it's work fine now.

**Comment by smash-necros** [comment]
Thanks

вс, 10 апр. 2022 г., 21:14 Charlie85270 ***@***.***>:
