### ISSUE TITLE
A-pool

### ISSUE THREAD

**Issue by article-i** [Charlie85270/conflux-pos-pools#14]
{
"name": "A-Pool",
"adress": "cfx:acdmgjnam0kmtnnnwhz4mh727akfxj7fg2gy3bamw6",
"image": "https://scan-icons.oss-cn-hongkong.aliyuncs.com/mainnet/cfx%3Aacbh1a67t82386g8yu5u895pytx93hbwsyktky4fdd.png",
"link": "https://v2.artii.cc/pool"
}

**Comment by Charlie85270** [comment]
Added with : [1bcd7ed](https://github.com/Charlie85270/conflux-pos-pools/commit/1bcd7edd4e1b69e9a0811861f0db0145b1c0f9fb)
