### ISSUE TITLE
A-pool now is active ，please update the status~~

### ISSUE THREAD

**Issue by article-i** [Charlie85270/conflux-pos-pools#19]

**Comment by Charlie85270** [comment]
The status is automatically updated from the live blockchain data. If is still inactive and your pool is active, please verify the addresses configuration for your pool on the pools.json file.

**Comment by Charlie85270** [comment]
Seems that there is an issue with your contract to get the poolSummary. 
Do you use the official Pool contracts ? https://github.com/conflux-fans/pos-pool/tree/main/contract

**Comment by article-i** [comment]
i have checked,; I'm not use the official Pool contracts; but in genreral, have the same 'poolsummary' function;but the value attribute have a little difference；
eg：
struct PoolSummary {
    uint256 available;
    uint256 interest; // PoS pool interest share
    uint256 totalInterest; // total interest of whole pools
    uint256 ACFX_holders_num;
    uint256 ACFX_sum;
  }
the official is：
struct PoolSummary {
    uint256 available;
    uint256 interest; // PoS pool interest share
    uint256 totalInterest; // total interest of whole pools
  }
Maybe there is a compatibility problem with your front end code？

**Comment by article-i** [comment]
others： stakerNumber() is the same as offical，poolAPY() is the same too；public variable ‘poolUserShareRatio’ is not changed

**Comment by article-i** [comment]
https://confluxscan.io/address/cfx:acdmgjnam0kmtnnnwhz4mh727akfxj7fg2gy3bamw6

**Comment by article-i** [comment]
i have tried to verify，but not success:"The resulting bytecode does NOT match with the bytecode that is stored on the address", i don't know the reason of it. so can you give error information? most of the function of  our contracts is the same as offical.

**Comment by Thegaram** [comment]
You'll need to make sure that the source code, compiler version, and optimizer parameters are exactly the same as what you used during deployment.
