### ISSUE TITLE
Summary info not show correctly 

### ISSUE THREAD

**Issue by Pana** [Charlie85270/conflux-pos-pools#21]
<img width="1332" alt="Screen Shot 2022-09-07 at 16 13 36" src="https://user-images.githubusercontent.com/552081/188826721-a34842df-78ce-44b2-9bb0-7fe2eda8e20b.png">

Maybe it's caused by scan API change

**Comment by Charlie85270** [comment]
Fixed with : https://github.com/Charlie85270/conflux-pos-pools/commit/c19d73f8e79f48550268b9cfd014970b742ffda7
